### ISSUE TITLE
Followers Doesn't Work

### ISSUE THREAD

**Issue by DayCamm** [mohammadraquib/IGFlash#2]
Hi,
is it only me, or when I try to request some followers I don't receive nothing?

I've also tried to give the account username of the account but I don't receive any followers..
Do you have any fix?

Thank you :-)

**Comment by mohammadraquib** [comment]
No, it's not just you, many users are having this problem so, we are creating a new version and I'll make sure that it doesn't happens in the new version.

**Comment by DayCamm** [comment]
Don't worry!
I'll wait :-)
Anyway, it's a very great service!

Thank you so much for your fast answer, 
have a nice day

**Comment by Karanvjveriyan** [comment]
Am Waiting for The Igflsh website update... When U will Open 🔓 the
Website?

**Comment by mohammadraquib** [comment]
Hi @Karanvjveriyan , I’ll be releasing this update by the end of this month.

**Comment by Karanvjveriyan** [comment]
What Are The Features You've Added? Anything New or Only Interface Update?
:)

**Comment by mohammadraquib** [comment]
@Karanvjveriyan there are a lot of new improvements and this time we'll make a minimal interface.
